var _ = require('underscore');

var messages = [
	"loves this with some of their heart",
	"loves this with precisely 25/3rds of their heart",
	"loves this with all of someone elseʼs heart. Ew",
	"loves this with the power of a thousand suns",
	"loves this more as a friend than like *that*, sorry",
	"tried, but just canʼt stop loving this",
	"would elope with this, if it were human",
	"enjoys this more than a sack oʼ scissors",
	"is shy, but wants to tell this they \"like like\" it",
	"shuns all others before this, at least until the next one",
	"wrote something not dissimilar to a love poem about this",
	"has attributed affection to this",
	"had an itch, but this scratched it",
	"can probably live without this, but would rather not",
	"is codependent with this",
	"canʼt fight this feelinʼ",
	"wants to show this their dancing",
	"wants to show this their feels",
	"used a pick-up line on this song and almost succeeded",
	"stalks this fondly from afar",
	"was wondering if this was doing anything tonight",
	"just put this on their sex playlist",
	"loves this in a way only a mother could",
	"left their betrothed at the altar for this",
	"is OVER NINE-THOUSAND for this",
	"has found their Precious",
	"had a heart palpitation because of this",
	"is taking this to a ~classy~ love hotel",
	"yup.",
	"b-baka! Itʼs not like I like this or anything, I just wanted to click the button, okay?",
	"awkardly displayed their amorous intent",
	"wants to move in together with this, but this is like “Woah, slow it down”",
	"serenaded this with a boombox",
	"passed a note to this during class",
	"has a warm, squiggly feeling for this in their heart",
	"okay.",
	"sure.",
	"fine.",
	"yeah.",
	"gets all blushy-wushy and nervous-pervous around this",
	"ʼs heart will go on",
	"struck by love at first sync",
	"built a love shrine for this in their closet. Donʼt worry, just a small one.",
	"ʼs grandest wish just came true",
	"has redeployed all available affection for an all out assault on this",
	"♥ ♥ ♥ ♥ ♥ ♥ ♥ ♥ ♥ ♥",
	"wants to grow old with this",
	"needs some space, theyʼre trying to start an unrequited love here!",
	"made a pot pie for this",
	"has initiated the mating dance",
	"is blushing somethinʼ fierce",
	"made eye contact with this, then ran away crying",
	"prays to this",
	"canʼt shake this feeling",
	"eternally bound their soul to this",
	"has separation anxiety when this isn't around",
	"self.loves.add(this);",
	"so loved this that they gave their only heart for its sins",
	"thinks this is kawaii uguuu",
	"UNCAUGHTEXCEPTIONERROR",
	"(╯♥□♥）╯︵ ┻━┻",
	"thinks this is THE BEST THE BEST THE BEST THE BEST THE BEST THE BEST THE BEST THE BEST...",
	"approves this",
	"made a non-volatile entry into their eternal heart database",
	"would draw this like one of their french girls",
	"called this while still on the first date",
	"touched this inappropriately"
];

module.exports = function(){
	return _.sample( messages );
};
